export const services = [
  {
    id: 'digital',
    number: '01',
    title: 'Digital Solutions',
    tagline: 'Build your digital presence',
    color: 'blue',
    icon: '💻',
    items: [
      'Website Design & Development',
      'Mobile App Development',
      'Web Application Development',
      'E-Commerce Solutions',
      'SEO & Performance Optimization',
      'UI/UX Design',
    ],
  },
  {
    id: 'cloud',
    number: '02',
    title: 'Cloud & DevOps Services',
    tagline: 'Scale with confidence',
    color: 'gold',
    icon: '☁️',
    items: [
      'AWS Cloud Architecture',
      'Cloud Migration & Deployment',
      'CI/CD Pipeline Automation',
      'Docker & Kubernetes (Containerization)',
      'Infrastructure as Code (Terraform, CloudFormation)',
      'Monitoring & Logging (CloudWatch, Prometheus, Grafana)',
      'Cloud Security & IAM',
      'Cost Optimization & Performance Scaling',
    ],
  },
  {
    id: 'automation',
    number: '03',
    title: 'Business Automation',
    tagline: 'Work smarter, not harder',
    color: 'purple',
    icon: '⚙️',
    items: [
      'Custom Business Systems',
      'CRM & Workflow Automation',
      'API Integrations',
      'Process Digitization',
      'Data Management Solutions',
      'Reporting & Dashboards',
    ],
  },
  {
    id: 'advisory',
    number: '04',
    title: 'Business Advisory',
    tagline: 'Strategic guidance for growth',
    color: 'orange',
    icon: '📊',
    items: [
      'Business Strategy & Planning',
      'Market Research & Analysis',
      'Financial Advisory',
      'Risk Management',
      'Process Improvement',
      'Compliance & Governance',
    ],
  },
  {
    id: 'development',
    number: '05',
    title: 'Business Development & Management',
    tagline: 'Grow, manage, succeed',
    color: 'green',
    icon: '📈',
    items: [
      'Business Growth Strategies',
      'Sales & Marketing Support',
      'Operations Management',
      'Team Development',
      'Project Management',
      'Performance Monitoring',
    ],
  },
]

export const colorMap: Record<string, string> = {
  blue: 'from-blue-brand to-blue-mid border-blue-brand/30',
  gold: 'from-gold to-gold-light border-gold/30',
  purple: 'from-purple-700 to-purple-500 border-purple-500/30',
  orange: 'from-orange-600 to-orange-400 border-orange-400/30',
  green: 'from-green-700 to-green-500 border-green-500/30',
}

export const iconBg: Record<string, string> = {
  blue: 'bg-blue-brand/10 text-blue-400',
  gold: 'bg-gold/10 text-gold',
  purple: 'bg-purple-500/10 text-purple-400',
  orange: 'bg-orange-500/10 text-orange-400',
  green: 'bg-green-500/10 text-green-400',
}
